/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Provider;

import Business.EcoSystem;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.StateNetwork;
import Business.Organization.HospitalOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author darsh
 */

     


public class ProviderWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProviderWorkAreaJPanel
     */
    
    private final JPanel userProcessContainer;
    private final UserAccount userAccount;
    private final HospitalEnterprise enterprise;
    private final HospitalOrganization organization;
    private final EcoSystem business;
    private final StateNetwork state;
    
    public ProviderWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount, HospitalEnterprise enterprise, HospitalOrganization organization, EcoSystem business, StateNetwork state) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.organization = organization;
        this.business = business;
        this.state = state;

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        workContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnvaccorder = new javax.swing.JButton();
        btnmanorder = new javax.swing.JButton();
        btnviewinven = new javax.swing.JButton();
        btnadminvacc = new javax.swing.JButton();
        btnviewadminvacc = new javax.swing.JButton();
        btnremoteclin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(240);

        workContainer.setBackground(new java.awt.Color(102, 153, 255));
        workContainer.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ICONS/11122021icons/delivery.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        workContainer.add(jPanel1, "card2");

        jSplitPane1.setRightComponent(workContainer);

        mainMenu.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Main Menu:");

        btnvaccorder.setBackground(new java.awt.Color(0, 0, 102));
        btnvaccorder.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnvaccorder.setForeground(new java.awt.Color(255, 255, 255));
        btnvaccorder.setText("Place Vaccine Order");
        btnvaccorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaccorderActionPerformed(evt);
            }
        });

        btnmanorder.setBackground(new java.awt.Color(0, 0, 102));
        btnmanorder.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnmanorder.setForeground(new java.awt.Color(255, 255, 255));
        btnmanorder.setText("Manage Orders");
        btnmanorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanorderActionPerformed(evt);
            }
        });

        btnviewinven.setBackground(new java.awt.Color(0, 0, 102));
        btnviewinven.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnviewinven.setForeground(new java.awt.Color(255, 255, 255));
        btnviewinven.setText("View Inventory");
        btnviewinven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewinvenActionPerformed(evt);
            }
        });

        btnadminvacc.setBackground(new java.awt.Color(0, 0, 102));
        btnadminvacc.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnadminvacc.setForeground(new java.awt.Color(255, 255, 255));
        btnadminvacc.setText("Administer Vaccine");
        btnadminvacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminvaccActionPerformed(evt);
            }
        });

        btnviewadminvacc.setBackground(new java.awt.Color(0, 0, 102));
        btnviewadminvacc.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnviewadminvacc.setForeground(new java.awt.Color(255, 255, 255));
        btnviewadminvacc.setText("View Administered Vaccines");
        btnviewadminvacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewadminvaccActionPerformed(evt);
            }
        });

        btnremoteclin.setBackground(new java.awt.Color(0, 0, 102));
        btnremoteclin.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnremoteclin.setForeground(new java.awt.Color(255, 255, 255));
        btnremoteclin.setText("Manage Remote Clinic Orders");
        btnremoteclin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoteclinActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PROVIDER");

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnvaccorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmanorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnviewinven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnadminvacc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnviewadminvacc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnremoteclin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addComponent(btnvaccorder)
                .addGap(18, 18, 18)
                .addComponent(btnmanorder)
                .addGap(18, 18, 18)
                .addComponent(btnviewinven)
                .addGap(18, 18, 18)
                .addComponent(btnadminvacc)
                .addGap(18, 18, 18)
                .addComponent(btnviewadminvacc)
                .addGap(18, 18, 18)
                .addComponent(btnremoteclin)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(mainMenu);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnremoteclinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoteclinActionPerformed
        // TODO add your handling code here:
        ManageClinicOrdersJPanel panel = new ManageClinicOrdersJPanel(workContainer, enterprise, organization, userAccount, business, state);
        workContainer.add("ManageSatelliteOrdersJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnremoteclinActionPerformed

    private void btnviewadminvaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewadminvaccActionPerformed
        // TODO add your handling code here:
        AdministeredVaccineListJPanel panel = new AdministeredVaccineListJPanel(workContainer, enterprise);
        workContainer.add("AdministeredVaccineListJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnviewadminvaccActionPerformed

    private void btnadminvaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminvaccActionPerformed
        // TODO add your handling code here:
        AdministerVaccineJPanel panel = new AdministerVaccineJPanel(workContainer, enterprise, organization, userAccount, business, state);
        workContainer.add("AdministerVaccineJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnadminvaccActionPerformed

    private void btnviewinvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewinvenActionPerformed
        // TODO add your handling code here:
        ViewInventoryJPanel panel = new ViewInventoryJPanel(workContainer, business, enterprise, organization);
        workContainer.add("ViewInventoryJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);

    }//GEN-LAST:event_btnviewinvenActionPerformed

    private void btnmanorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanorderActionPerformed
        // TODO add your handling code here:
        ManageOrdersJPanel panel = new ManageOrdersJPanel(workContainer, enterprise, organization, userAccount, business, state);
        workContainer.add("ManageOrdersJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnmanorderActionPerformed

    private void btnvaccorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaccorderActionPerformed
        // TODO add your handling code here:
        PlaceVaccineOrderJPanel panel = new PlaceVaccineOrderJPanel(workContainer, enterprise, organization, userAccount, business, state);
        workContainer.add("PlaceVaccineOrderJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnvaccorderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadminvacc;
    private javax.swing.JButton btnmanorder;
    private javax.swing.JButton btnremoteclin;
    private javax.swing.JButton btnvaccorder;
    private javax.swing.JButton btnviewadminvacc;
    private javax.swing.JButton btnviewinven;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel workContainer;
    // End of variables declaration//GEN-END:variables
}
