/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.SystemAdmin;

import Business.EcoSystem;
import Business.Disease.Disease;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author riyavirani
 */
public class AddNewDiseaseInfoJPanel extends javax.swing.JPanel {

    private final JPanel workContainer;
    private final EcoSystem business;
    /**
     * Creates new form AddNewDiseaseInfoJPanel
     */
    public AddNewDiseaseInfoJPanel(JPanel workContainer, EcoSystem business) {
        initComponents();
        this.workContainer = workContainer;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdateUpdateDate = new com.toedter.calendar.JDateChooser();
        lblLastUpdateDate = new javax.swing.JLabel();
        txtDiseaseCode = new javax.swing.JTextField();
        txtDiseaseName = new javax.swing.JTextField();
        btnAddDiseaseInformation = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblDiseaseCode = new javax.swing.JLabel();
        lblDiseaseName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jdateUpdateDate.setDateFormatString(" MMM, d yyyy");

        lblLastUpdateDate.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblLastUpdateDate.setForeground(new java.awt.Color(0, 0, 102));
        lblLastUpdateDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLastUpdateDate.setText("Last Updated on:");

        btnAddDiseaseInformation.setBackground(new java.awt.Color(0, 0, 102));
        btnAddDiseaseInformation.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnAddDiseaseInformation.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDiseaseInformation.setText("Add Disease Info");
        btnAddDiseaseInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDiseaseInformationActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add New Disease Information");

        lblDiseaseCode.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblDiseaseCode.setForeground(new java.awt.Color(0, 0, 102));
        lblDiseaseCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiseaseCode.setText("Disease Code:");

        lblDiseaseName.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblDiseaseName.setForeground(new java.awt.Color(0, 0, 102));
        lblDiseaseName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiseaseName.setText("Disease Name:");

        btnBack.setBackground(new java.awt.Color(0, 0, 102));
        btnBack.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLastUpdateDate)
                                    .addComponent(lblDiseaseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDiseaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiseaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiseaseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdateUpdateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddDiseaseInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 223, Short.MAX_VALUE))
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiseaseCode)
                    .addComponent(txtDiseaseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiseaseName)
                    .addComponent(txtDiseaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastUpdateDate)
                    .addComponent(jdateUpdateDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddDiseaseInformation)
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDiseaseInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDiseaseInformationActionPerformed
        // TODO add your handling code here:
        String diseaseCode = txtDiseaseCode.getText();
        if(diseaseCode.trim().equalsIgnoreCase(""))
        {JOptionPane.showMessageDialog(null, "Please enter a disease Code");
            return;

        }
        String diseaseName = txtDiseaseName.getText();
        if(diseaseName.trim().equalsIgnoreCase(""))
        {JOptionPane.showMessageDialog(null, "Please enter a disease Name");
            return;

        }

        Date lastUpdatedDate = jdateUpdateDate.getDate();

        for(Disease d : business.getDiseaseDirectory().getdiseaseDirectory())
        {
            if(d.getDiseaseCode().equalsIgnoreCase(diseaseCode) && d.getDiseaseName().equalsIgnoreCase(diseaseName))
            {
                JOptionPane.showMessageDialog(null, "Disease exists!");
                return;
            }
        }

        Disease disease = business.getDiseaseDirectory().addNewDisease();
        disease.setDiseaseCode(diseaseCode);
        disease.setDiseaseName(diseaseName);
        disease.setLastUpdatedTime(lastUpdatedDate);

    }//GEN-LAST:event_btnAddDiseaseInformationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDiseaseInformation;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JDateChooser jdateUpdateDate;
    private javax.swing.JLabel lblDiseaseCode;
    private javax.swing.JLabel lblDiseaseName;
    private javax.swing.JLabel lblLastUpdateDate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDiseaseCode;
    private javax.swing.JTextField txtDiseaseName;
    // End of variables declaration//GEN-END:variables
}
