/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package UserInterface.SystemAdmin;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
//import UserInterface.UpdateUserAccountJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author riyavirani
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
     private final JPanel userProcessContainer;
    private final EcoSystem business;
    private final UserAccount userAccount;
    
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem business, UserAccount userAccount ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.userAccount = userAccount;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        workContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mainMenuContainer = new javax.swing.JPanel();
        btnManageState = new javax.swing.JButton();
        btnManageCity = new javax.swing.JButton();
        btnManageManufacturer = new javax.swing.JButton();
        btnManageProvider = new javax.swing.JButton();
        btnManageDrugCatalog = new javax.swing.JButton();
        btnManageDiseaseCatalog = new javax.swing.JButton();
        btnManageUserAccount = new javax.swing.JButton();
        lblSysAdmin = new javax.swing.JLabel();

        setForeground(new java.awt.Color(204, 204, 255));
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBackground(new java.awt.Color(0, 0, 102));
        jSplitPane1.setDividerLocation(210);
        jSplitPane1.setForeground(new java.awt.Color(204, 204, 255));

        workContainer.setBackground(new java.awt.Color(102, 153, 255));
        workContainer.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        workContainer.add(jPanel1, "card2");

        jSplitPane1.setRightComponent(workContainer);

        mainMenuContainer.setBackground(new java.awt.Color(255, 255, 204));

        btnManageState.setBackground(new java.awt.Color(0, 0, 102));
        btnManageState.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnManageState.setForeground(new java.awt.Color(255, 255, 255));
        btnManageState.setText("Manage States ");
        btnManageState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStateActionPerformed(evt);
            }
        });

        btnManageCity.setBackground(new java.awt.Color(0, 0, 102));
        btnManageCity.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnManageCity.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCity.setText("Manage Cities");
        btnManageCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCityActionPerformed(evt);
            }
        });

        btnManageManufacturer.setBackground(new java.awt.Color(0, 0, 102));
        btnManageManufacturer.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnManageManufacturer.setForeground(new java.awt.Color(255, 255, 255));
        btnManageManufacturer.setText("Manage Manufacturers");
        btnManageManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageManufacturerActionPerformed(evt);
            }
        });

        btnManageProvider.setBackground(new java.awt.Color(0, 0, 102));
        btnManageProvider.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnManageProvider.setForeground(new java.awt.Color(255, 255, 255));
        btnManageProvider.setText("Manage Providers");
        btnManageProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProviderActionPerformed(evt);
            }
        });

        btnManageDrugCatalog.setBackground(new java.awt.Color(0, 0, 102));
        btnManageDrugCatalog.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnManageDrugCatalog.setForeground(new java.awt.Color(255, 255, 255));
        btnManageDrugCatalog.setText("Manage Drug Catalog");
        btnManageDrugCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDrugCatalogActionPerformed(evt);
            }
        });

        btnManageDiseaseCatalog.setBackground(new java.awt.Color(0, 0, 102));
        btnManageDiseaseCatalog.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnManageDiseaseCatalog.setForeground(new java.awt.Color(255, 255, 255));
        btnManageDiseaseCatalog.setText("Manage Disease Catalog");
        btnManageDiseaseCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDiseaseCatalogActionPerformed(evt);
            }
        });

        btnManageUserAccount.setBackground(new java.awt.Color(0, 0, 102));
        btnManageUserAccount.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnManageUserAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnManageUserAccount.setText("Manage User Accounts");
        btnManageUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserAccountActionPerformed(evt);
            }
        });

        lblSysAdmin.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblSysAdmin.setForeground(new java.awt.Color(0, 0, 102));
        lblSysAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSysAdmin.setText("SYSTEM ADMIN");

        javax.swing.GroupLayout mainMenuContainerLayout = new javax.swing.GroupLayout(mainMenuContainer);
        mainMenuContainer.setLayout(mainMenuContainerLayout);
        mainMenuContainerLayout.setHorizontalGroup(
            mainMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageDrugCatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageDiseaseCatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageUserAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageManufacturer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageProvider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSysAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainMenuContainerLayout.setVerticalGroup(
            mainMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblSysAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnManageState)
                .addGap(18, 18, 18)
                .addComponent(btnManageCity)
                .addGap(18, 18, 18)
                .addComponent(btnManageManufacturer)
                .addGap(18, 18, 18)
                .addComponent(btnManageProvider)
                .addGap(18, 18, 18)
                .addComponent(btnManageDiseaseCatalog)
                .addGap(18, 18, 18)
                .addComponent(btnManageDrugCatalog)
                .addGap(18, 18, 18)
                .addComponent(btnManageUserAccount)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(mainMenuContainer);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserAccountActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel panel = new ManageUserAccountJPanel(workContainer, business);
        workContainer.add("ManageUserAccountJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnManageUserAccountActionPerformed

    private void btnManageDiseaseCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDiseaseCatalogActionPerformed
        // TODO add your handling code here:
        ManageDiseaseCatalogJPanel panel = new ManageDiseaseCatalogJPanel(workContainer, business);
        workContainer.add("ManageDiseaseCatalogJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnManageDiseaseCatalogActionPerformed

    private void btnManageDrugCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDrugCatalogActionPerformed
        // TODO add your handling code here:
        ManageDrugCatalogJPanel panel = new ManageDrugCatalogJPanel(workContainer, business);
        workContainer.add("ManageVaccineCatalogJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnManageDrugCatalogActionPerformed

    private void btnManageProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProviderActionPerformed
        // TODO add your handling code here:
        ManageProviderDetailsJPanel panel = new ManageProviderDetailsJPanel(workContainer, business);
        workContainer.add("ManageProviderJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnManageProviderActionPerformed

    private void btnManageManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageManufacturerActionPerformed
        // TODO add your handling code here:
        ManageManufacturerDetailsJPanel panel = new ManageManufacturerDetailsJPanel(workContainer, business);
        workContainer.add("ManageManufacturersJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnManageManufacturerActionPerformed

    private void btnManageCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCityActionPerformed
        // TODO add your handling code here:
        ManageCityListJPanel panel = new ManageCityListJPanel(workContainer, business);
        workContainer.add("ManageCityJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnManageCityActionPerformed

    private void btnManageStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStateActionPerformed
        // TODO add your handling code here:
        ManageStateJPanel panel = new ManageStateJPanel(workContainer, business);
        workContainer.add("ManageStateJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnManageStateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCity;
    private javax.swing.JButton btnManageDiseaseCatalog;
    private javax.swing.JButton btnManageDrugCatalog;
    private javax.swing.JButton btnManageManufacturer;
    private javax.swing.JButton btnManageProvider;
    private javax.swing.JButton btnManageState;
    private javax.swing.JButton btnManageUserAccount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblSysAdmin;
    private javax.swing.JPanel mainMenuContainer;
    private javax.swing.JPanel workContainer;
    // End of variables declaration//GEN-END:variables
}
